linux_task:
  container:
    image: alpine:latest
  env:
    - GOPROXY: https://proxy.golang.org
  setup_script:
    - apk add go
    - export GOPATH=$(pwd)/go
    - export PATH=$GOPATH/bin:$PATH
    - mkdir ${GOPATH}/src/${CIRRUS_REPO_OWNER}
    - cd ${GOPATH}/src/${CIRRUS_REPO_OWNER}
    - git clone https://${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git
    - cd ${CIRRUS_REPO_NAME}
    - git checkout ${CIRRUS_BRANCH}
  build_script:
    - go version
    - go build -race -v ./...
  test_script:
    - go test -race -count=100 ./...
    - go test -race -v -count=1 ./...
