linux_task:
  container:
    image: alpine:latest
  env:
    GOPATH: ${CIRRUS_WORKING_DIR}/go
    PATH: ${GOPATH}/bin:${PATH}
    GOPROXY: https://proxy.golang.org
  setup_script:
    - apk add go
    - mkdir ${GOPATH}/go/${CIRRUS_REPO_FULL_NAME}
    - cd ${GOPATH}/go/${CIRRUS_REPO_FULL_NAME}
  clone_script: |
    if [[ -z "$CIRRUS_PR" ]]; then
      git clone --recursive --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $(pwd)
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    else
      git clone --recursive https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $(pwd)
      git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    fi
  build_script:
    - go version
    - go build -race -v ./...
  test_script:
    - go test -race -count=100 ./...
    - go test -race -v -count=1 ./...
