version: '{build}'

platform: Any CPU

clone_folder: c:\go\src\github.com\awnumar\memguard

environment:
  GOPATH: c:\go

install:
- set PATH=C:\msys64\mingw64\bin;%PATH%
- set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
- go version

build_script:
- go build -race -v .

test_script:
- go test -race -v ./...
- go test -count=1000 -race ./...
